=== yunju-m/Embeded-KITA2024-Lecture-vscode/html/xml/dtd/computers.dtd
<!DOCTYPE computers
[
<!ELEMENT computers (computer)>
<!ELEMENT computer (cpu, memory, gpu)>
<!ELEMENT cpu (#PCDATA)>
<!ELEMENT memory (#PCDATA)>
<!ELEMENT gpu (#PCDATA)>
]>

=== yunju-m/Embeded-KITA2024-Lecture-vscode/html/xml/computer.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- <!DOCTYPE computers SYSTEM "dtd/computers.dtd"> -->
<?xml-stylesheet type="text/css" href="css/computer.css"?>
<computers xmlns="localhost" xmlns:xsi="localhost/xsi" 
    xsi:schemaLocation="schema/computers.xsd">
    <computer>
        <cpu>I9</cpu>
        <memory>16G</memory>
        <gpu>1660</gpu>
    </computer>
    <computer>
        <cpu>I7</cpu>
        <memory>8G</memory>
        <gpu>1060</gpu>
    </computer>
</computers>
